import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Code, Copy, Check } from 'lucide-react';
import { toast } from 'sonner';

interface EmbedGeneratorProps {
    previewUrl: string;
}

export default function EmbedGenerator({ previewUrl }: EmbedGeneratorProps) {
    const [copied, setCopied] = useState(false);

    const embedCode = `<div style="text-align: center;">
  <img src="${previewUrl}" alt="QR Code" style="max-width: 100%; height: auto; border-radius: 8px;" />
  <p style="font-family: sans-serif; font-size: 12px; color: #666; margin-top: 8px;">Generated by <a href="https://qrafted.app" style="color: #3b82f6; text-decoration: none;">Qrafted</a></p>
</div>`;

    const handleCopy = () => {
        navigator.clipboard.writeText(embedCode);
        setCopied(true);
        toast.success("Embed code copied to clipboard");
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <Dialog>
            <DialogTrigger asChild>
                <Button variant="outline" size="sm" className="gap-2">
                    <Code className="w-4 h-4" />
                    Embed
                </Button>
            </DialogTrigger>
            <DialogContent className="sm:max-w-lg text-left">
                <DialogHeader>
                    <DialogTitle>Embed QR Code</DialogTitle>
                </DialogHeader>
                <div className="space-y-4 py-4">
                    <p className="text-sm text-muted-foreground">
                        Copy this snippet to embed your custom QR code on any website or blog.
                    </p>
                    <div className="relative group">
                        <pre className="p-4 bg-secondary rounded-lg text-xs font-mono overflow-x-auto whitespace-pre-wrap leading-relaxed border border-border">
                            {embedCode}
                        </pre>
                        <Button
                            size="icon"
                            variant="secondary"
                            className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity"
                            onClick={handleCopy}
                        >
                            {copied ? <Check className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4" />}
                        </Button>
                    </div>
                    <div className="p-4 border border-primary/20 bg-primary/5 rounded-lg">
                        <h4 className="text-xs font-bold uppercase tracking-wider mb-2">Live Preview</h4>
                        <div dangerouslySetInnerHTML={{ __html: embedCode }} className="flex justify-center" />
                    </div>
                </div>
            </DialogContent>
        </Dialog>
    );
}
