import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Code, Copy, Check, Eye } from 'lucide-react';
import { toast } from 'sonner';
import { motion } from 'framer-motion';

interface EmbedGeneratorProps {
    previewUrl: string;
}

export default function EmbedGenerator({ previewUrl }: EmbedGeneratorProps) {
    const [copied, setCopied] = useState(false);

    const embedCode = `<div style="text-align: center;">
  <img src="${previewUrl}" alt="QR Code" style="max-width: 100%; height: auto; border-radius: 8px;" />
  <p style="font-family: sans-serif; font-size: 12px; color: #666; margin-top: 8px;">Generated by <a href="https://qrafted.app" style="color: #3b82f6; text-decoration: none;">Qrafted</a></p>
</div>`;

    const handleCopy = () => {
        navigator.clipboard.writeText(embedCode);
        setCopied(true);
        toast.success("Embed code copied to clipboard");
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <Dialog>
            <DialogTrigger asChild>
                <Button variant="outline" className="gap-2 border-slate-200 hover:bg-slate-50 hover:border-primary/30">
                    <Code className="w-4 h-4" />
                    <span className="hidden sm:inline">Embed</span>
                </Button>
            </DialogTrigger>
            <DialogContent className="sm:max-w-lg glass-strong border-slate-200 p-0 overflow-hidden">
                <div className="p-6 pb-4">
                    <DialogHeader>
                        <DialogTitle className="flex items-center gap-2 text-xl font-bold">
                            <div className="w-8 h-8 rounded-lg gradient-bg flex items-center justify-center">
                                <Code className="w-4 h-4 text-white" />
                            </div>
                            Embed QR Code
                        </DialogTitle>
                    </DialogHeader>
                </div>

                <div className="px-6 pb-6 space-y-5">
                    <p className="text-sm text-muted-foreground">
                        Copy this HTML snippet to embed your QR code on any website or blog.
                    </p>

                    {/* Code block */}
                    <div className="relative group">
                        <pre className="p-4 bg-slate-900 text-slate-300 rounded-xl text-[11px] font-mono overflow-x-auto whitespace-pre-wrap break-all leading-relaxed max-h-[140px] overflow-y-auto">
                            {embedCode}
                        </pre>
                        <Button
                            size="sm"
                            className={`absolute top-3 right-3 transition-all ${
                                copied 
                                    ? 'bg-emerald-500 hover:bg-emerald-500' 
                                    : 'bg-slate-700 hover:bg-slate-600'
                            }`}
                            onClick={handleCopy}
                        >
                            {copied ? (
                                <>
                                    <Check className="w-3.5 h-3.5 mr-1.5" />
                                    Copied!
                                </>
                            ) : (
                                <>
                                    <Copy className="w-3.5 h-3.5 mr-1.5" />
                                    Copy
                                </>
                            )}
                        </Button>
                    </div>

                    {/* Preview */}
                    <div className="space-y-3">
                        <div className="flex items-center gap-2 text-sm font-medium text-foreground">
                            <Eye className="w-4 h-4 text-muted-foreground" />
                            Live Preview
                        </div>
                        <div className="p-6 bg-slate-50 rounded-xl border border-slate-200">
                            <div
                                dangerouslySetInnerHTML={{ __html: embedCode }}
                                className="flex justify-center"
                            />
                        </div>
                    </div>
                </div>
            </DialogContent>
        </Dialog>
    );
}
